### ISSUE TITLE
comments are broken

### ISSUE THREAD

**Issue by FlashlightET** [lightbeam24/TubeK12#1]
![image](https://user-images.githubusercontent.com/29938499/179314259-d24e5120-1d88-40c2-b987-42ae089102a8.png)
might be a chrome specific bug, or youtube breaking things, but there is a huge whitespace above the comments that shouldnt be there as well as a ton of other alignment wonks

**Comment by lightbeam24** [comment]
Sorry I never got to this issue. I tried to address some of those problems in the latest update, but there is still work to be done.

**Comment by lightbeam24** [comment]
Closing as not planned as TubeK12 is discontinued and this repository is about to be archived.
