### ISSUE TITLE
Channel Page Broken

### ISSUE THREAD

**Issue by staticZeRo** [lightbeam24/TubeK12#2]
for some reason whenever i have this extension enabled (using chrome) I go to a channel page and its broken and idk what happened
!
![broken](https://user-images.githubusercontent.com/122331446/212502679-9845304c-60dc-45ab-8bea-01fae1660d90.jpg)

**Comment by lightbeam24** [comment]
It's because channel urls start with "@" now. It's fixed in update I'm about to release.

**Comment by staticZeRo** [comment]
> It's because channel urls start with "@" now. It's fixed in update I'm about to release.

ah okay, that makes sense
