### ISSUE TITLE
Broken previews of videos on the home page.

### ISSUE THREAD

**Issue by nullcat0ru** [lightbeam24/TubeK12#3]
Saw your layout for Youtube, and I really liked it.  But on the main page I noticed that the videos for some reason are not going down as it should be on the screenshot, but are grouped together for some reason
I tried it on Edge browser and turned on the option "Non-Firefox users must turn this option on", but even if you turn it off nothing changes, in Firefox itself - it works perfectly and no such bugs. Screenshots provided (where what browser signed in the screenshots)
![Снимок](https://github.com/lightbeam24/TubeK12/assets/49506503/5cbe158e-24c7-4574-946f-8eee3acd5447)
![Снимок2](https://github.com/lightbeam24/TubeK12/assets/49506503/aba12604-e489-40ec-a2aa-57664a8cc059)

**Comment by lightbeam24** [comment]
TubeK12 is discontinued, and I'm going to archive this repository in a couple minutes. My only suggestion is to use CustomTube, which is what I'm working on now. While it is currently exclusive to Firefox, I do plan to port it to Chromium.

https://addons.mozilla.org/en-CA/firefox/addon/customtube/
https://github.com/lightbeam24/customtube
