### ISSUE TITLE
My YouTube layout is completely broken with TubeK12

### ISSUE THREAD

**Issue by Aleksandra0056** [lightbeam24/TubeK12#4]
### Problem description:
- The video miniatures (thumbnails) are covered by the sidebar, and the show/hide sidebar is covered by the Channel Menu button and these buttons are misaligned. 
- If I hide the sidebar, then the new 2023 sidebar appears. 
- And video thumbnails, titles, and description animation is the same as 2023 layout.

### Expected results:
- The layout shouldn't be broken.
- The buttons should be aligned correctly.
- I think, that the sidebar wasn't hideable in 2012.
- And the video thumbnail, title, and description loading animation should be like 2012 too.

### Other details:
- Installed using [userChrome.css](https://www.userchrome.org/), or using [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)? Using Stylus
- Chrome, or Firefox? Firefox.
- TubeK12 version: 1.5.0.
- Browser version: Firefox v113.0.2
- YouTube site zoom percentage: 100%
- OS version: Windows 11 22621.1778
- OS architecture: 64-bit
- Browser architecture: 64-bit
- CPU: AMD A10-7860K 
- RAM: 16,0GB DDR3 
- Motherboard: MSI A88XM-E35 V2 
- Graphics: 1024MB ATI AMD Radeon R7 

#### Broken layout:
![image](https://github.com/lightbeam24/TubeK12/assets/69351811/4a9466a4-71f9-4590-80c7-fef9c2700ba1)
#### 2023 sidebar is appearing if sidebar is hidden, which is wrong:
![image](https://github.com/lightbeam24/TubeK12/assets/69351811/100d891a-7b6e-40f0-ae32-6c828267ec87)
#### The video thumbnail, title, and description loading animation is also wrong:
![image](https://github.com/lightbeam24/TubeK12/assets/69351811/c8458865-77b1-406c-9386-ef0d57e86c30)

**Comment by lightbeam24** [comment]
Oh, I guess I forgot to mention on here that TubeK12 is discontinued. Whoops. I'm now developing CustomTube, an extension that lets you choose your YouTube layout, including the 2012 layout. Use CustomTube instead, it should fix all of these issues.

https://addons.mozilla.org/en-CA/firefox/addon/customtube/
https://github.com/lightbeam24/customtube

What should I do to communicate that TubeK12 is discontinued? I already added "[Discontinued]" to the style's name on userstyles.world.

**Comment by Aleksandra0056** [comment]
> Oh, I guess I forgot to mention on here that TubeK12 is discontinued.

I'm proposing, that this repository should be archived if it is discontinued.

**Comment by lightbeam24** [comment]
Oh okay, I'll do that right away.
